#docker compose
version: '3.8'

services:
  mysql:
    container_name: mysql_local
    image: mysql:8.0.30
#    주의 : 파일명에 따라 alphabet 순으로 실행을한다.
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=pass_local
      - MYSQL_USER=pass_local_user
      - MYSQL_PASSWORD=passlocal123
      - MYSQL_ROOT_PASSWORD=passlocal123
      - TZ=Asia/Seoul